/**
 * Renders a JSON-LD <script> block. Server-rendered, so crawlers and AI
 * engines read the structured data straight from the HTML.
 */
export function JsonLd({ data }: { data: Record<string, unknown> }) {
  return (
    <script
      type="application/ld+json"
      // Structured data is static and trusted, generated by our own code.
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}
